// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID            int64   `json:"id"`
	Author        string  `json:"author"`
	ParentPost    string  `json:"parentPost"`
	ParentComment *string `json:"parentComment,omitempty"`
}

type Mutation struct {
}

type NewComment struct {
	Author        string  `json:"author"`
	ParentPost    string  `json:"parentPost"`
	ParentComment *string `json:"parentComment,omitempty"`
}

type NewPost struct {
	Author          string `json:"author"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Post struct {
	ID              int64  `json:"id"`
	Author          string `json:"author"`
	CommentsAllowed bool   `json:"commentsAllowed"`
}

type Query struct {
}
